sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
language: java
jdk:
- oraclejdk7
- oraclejdk8
env:
  global:
  - secure: FYG46Pj79jAhUFHZEd4v5n4w6TZysQHvrc5NN4wMpsrABqeZzAfO8Ma+BSE2Rh32IMQpIHMIOyr3WA++9LLl4BF0UrLcm9pWJMD2eccozdhwjlDfcVMTe2R4ui9hOT0WjAZ0UnJqHhOqR85rMjmOzE9E4x9x2ZlOQrDJdkxkLJVdv1aWG+w9VDzGCUwwqBYc0CEudNeDz2+YIxUPXwu50Fcu7CCNVXLkpy54uUB8An2XHxIZnZLQPBO9Kq40bis383EgEumDpvBlJdNL70tA+SC/YaDFqnZJBUAqh+ZBau+LT3/caCMV12SqcVTry/POJoTYqoHWb/HpL4szmNHQ4uxfZBmR+xDzWYY9CIcwGV7rX9Q8lK3iWccLFh+iz2/58OfoHmKxnPrt5dn14UB23Qb3QfWqB2po30L+tLVCEganDYHsTvWfpGnnWRBc6VDFuFS96z/Vh/SKOcP8BsHYiHMPw2m/SbADGz3WPtOy13i5r2X52B+J0RqVohfJOk6bnYz0gJLDWGD3OK5+qSwARIGzTBDhmdmYcXtUsGpjkglG9IaYZiHMoXe60TL9jselrTXUziUMKttUwyPcDv3+izBpoRTNTrq746d0BvEyHbR00gAjAh22bU3uKSRaOVx5u0Ou2MAk/m41ZjQZ7Svgc4YaCxY9lQf+wih/bqXvrkE=
  - secure: LS4ZF5M1G3MmCUPKvxA9G850diQB+BE6bdXFWPX+6XwryiuU+NhPJ/WzCbK/ycLxEc6T8CazEWub8x3mKdYZzdrwkpPBRLFG21WJAPtFFpFBZNGtzMLSLrsoQBcugYJG2L1xU5p+y0TAh+X9BX23YKpCRZVzgA1rjTDBqT6TYe7+DqkCqgh5NJPlQC62Bqi6pA7WFukO6KZtQiHSABgDpG8NoDRhPVgKHF+cJJPawu/kFy6Z/qPPQ0RTjVfi+ARC11IIr5xBY169URmwkVt/CTDS1ln/n0ySt+1gCzuwMvmqHdA+LFGD12nwc7niShQJY8rAiHn2dcP+chFHPGc2QLR4cO9I6IT0Z5LJL5DRTJHzxPumTWBuby4tWABV1F5G6JG1P55YLKyL8KUaSdHzeSmkRifkE9YsrYrgj8g6aqWHTUeoK0TRJ1IW9QcCZO1DuXW7SNMr8PXOteT1tSYYUoOqmP/EWdGJIDSIRM4saVxxzZ1eJxV/uc7k5gDMD9UeWWstPO9a7OO4Zcx2TtybTKBXsv3Z+ZBYg4vSazbusxD1tcXa7LPiT02vAmEye7VLLn0dXUXVu46vv8DIxreeMKzIpMdOk17j4HyCxIcMfsNprJKVoB8f328+Xd8eMSLV/hvVXIOBcxxYNWMKvrLINK1RCA3/qQSeK1G7KN7Ce/I=
