# name of the software
name: Funksjonell dokumentasjon for Posten signering.

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/signature-api-specification"

currentVersion: "1.0"
versions: ["1.0"]

collections:
  v1_0:   
    output: true
    permalink: /v1.0/

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/digipost/signature-api-specification
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/signature-api-specification
  - title: Issues
    url: https://github.com/digipost/signature-api-specification/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: signature-api-specification

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-77734017-1
  domain: auto

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
